---
- name: Install tools to allow transport of apt packages over https
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - software-properties-common
    - apt-transport-https

  # dpkg performs version checking automatically
- name: "Install .deb for graylog-collector"
  apt: 
    deb: "{{ graylog.debfile.url }}"
    state: present

- name: "Create graylog-collector service"
  command: graylog-collector-sidecar -service install

- name: "Copy over graylog config"
  template:
    src: collector_sidecar.yml 
    dest: /etc/graylog/collector-sidecar/collector_sidecar.yml
  notify:
    - "graylog_restart"
...
