---
- name: Install tools to allow transport of apt packages over https
  apt:
    name: ['software-properties-common', 'apt-transport-https']
    state: present


  # dpkg performs version checking automatically
- name: "Install .deb for graylog-sidecar"
  apt: 
    deb: "{{ graylog_debfile_url }}"
    state: present

- name: Install graylog_sidecar
  apt:
    name: "graylog-sidecar"
    state: present
    update_cache: yes

- name: "Create graylog-sidecar service"
  command: graylog-sidecar -service install
  ignore_errors: yes

- name: "Copy over graylog config"
  template:
    src: sidecar.yml 
    dest: /etc/graylog/sidecar/sidecar.yml
  notify:
    - "graylog_restart"
...
